# Generated by Django 4.1.5 on 2023-01-27 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBadgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Введите значение больше 0')], verbose_name='Высота, см')),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Введите значение больше 0')], verbose_name='Диаметр, см')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Введите значение больше 0')], verbose_name='Вес, кг')),
                ('light_loving', models.SmallIntegerField(blank=True, choices=[(1, 'Тень'), (2, 'Полутень'), (3, 'Свет')], verbose_name='Выбор светолюбивости')),
                ('period_from', models.SmallIntegerField(choices=[(None, 'Выберите месяц'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь')], default=5, verbose_name='Цветение с')),
                ('period_by', models.SmallIntegerField(choices=[(None, 'Выберите месяц'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь')], default=10, verbose_name='Цветение по')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'Characteristic',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='flowers/', verbose_name='Фото растения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Введите значение больше 0')], verbose_name='Цена, руб.')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'db_table': 'Flower',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('categorybadgebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flower.categorybadgebase')),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
                'db_table': 'Badge',
            },
            bases=('flower.categorybadgebase',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categorybadgebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flower.categorybadgebase')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='flower.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
            bases=('flower.categorybadgebase',),
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Интернет ресурс на растение')),
                ('flower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flower_qr', to='flower.flower', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
                'db_table': 'QR',
            },
        ),
        migrations.CreateModel(
            name='FlowerCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_flower', to='flower.characteristic', verbose_name='Характеристика')),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_char', to='flower.flower', verbose_name='Растение')),
            ],
            options={
                'db_table': 'FlowerCharacteristic',
            },
        ),
        migrations.AddField(
            model_name='characteristic',
            name='flower',
            field=models.ManyToManyField(through='flower.FlowerCharacteristic', to='flower.flower'),
        ),
        migrations.AddField(
            model_name='flower',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flower_badge', to='flower.badge', verbose_name='Бейдж'),
        ),
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='flower.category', verbose_name='Категория'),
        ),
    ]
